version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.06
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependcies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run: ./gradlew lint test
