version: 2.1

orbs:
  android: circleci/android@2.1.2

# 키 관련 context 추가해야함

references:
  exp: &exp
    filters:
      tags:
        only: /^v.*/
      branches:
        only:
          - /.*/

gradle_key: &gradle_key
              jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

executors:
    fastlane_executor:
      docker:
        - image: fastlanetools/ci:0.4.0
      resource_class: large

jobs:
  android_lint_test:
    executor: fastlane_executor
    steps:
      - checkout
      - restore_cache:
          key: *gradle_key
      - run:
          name: Download Dependcies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: *gradle_key
      - run:
          name: execute unit test lane
          command: fastlane check_test build_flavor:$BUILD_FLAVOR build_type:$BUILD_TYPE
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  android_unit_test:
    executor: fastlane_executor
    steps:
      - checkout
      - restore_cache:
          key: *gradle_key
      - run:
          name: Download Dependcies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: *gradle_key
      - run:
          name: execute unit test lane
          # TODO : fix build variant
          #command: fastlane unit_test build_flavor:exp build_type:${}
          command: fastlane test_for_test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  # this job is not working on local run
  android_ui_test:
    executor:
      # Image Tags
      # 2022.04.1,2022.03.1, 2022.01.1, 2021.12.1, 2021.10.1, 202102-01
      # https://circleci.com/developer/machine/image/android
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.04.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86

#  firebase_app_distribution:
#    <<: *exp
#    executor: test_executor
#    steps:
#      - checkout
#      - run:
#          name: configure build
#          command: bundle update fastlane && gem install bundler && bundle install
#      - run:
#          name: "Install Firebase CLI"
#          command: |
#            curl -sL firebase.tools | bash
#      - run:
#          name: "Deploy alpha build to Firebase"
#          command: |
#            bundle exec fastlane stage flavor:debug branch:${CIRCLE_BRANCH} app_id:$FIREBASE_APP_ID firebase_token:$FIREBASE_CLI_TOKEN

workflows:
  local_test:
    jobs:
      - android_unit_test:
        <<: *exp
