version: 2.1

executors:
  fastlane_executor:
    docker:
      - image: cimg/android:2022.09
    resource_class: large

# android test 에 필요함
orbs:
  android: circleci/android@2.1.2
  ruby: circleci/ruby@2.0.0

references:
    filters:
      tags:
        only: /^v.*/
      branches:
        only:
          - /.*/

gradle_key: &gradle_key
              jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

jobs:
  android_lint_test:
    executor: fastlane_executor
    steps:
      - checkout
      - restore_cache:
          key: *gradle_key
      - run:
          name: Download Dependcies
          command: |
           ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: *gradle_key
      - ruby/install-deps
      - run:
          name: execute unit test lane
          command: |
           fastlane check_test build_flavor:$BUILD_FLAVOR build_type:$BUILD_TYPE
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  android_unit_test:
    executor: fastlane_executor
    steps:
      - checkout
      - restore_cache:
          key: *gradle_key
      - run:
          name: Download Dependcies
          command: |
           ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: *gradle_key
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"
      - ruby/install-deps
      - run:
          name: execute unit test lane
          # TODO : fix build variant
          command: |
           bundle exec fastlane unit_test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  # this job is not working on local run
  android_ui_test:
    executor:
      # Image Tags
      # 2022.04.1,2022.03.1, 2022.01.1, 2021.12.1, 2021.10.1, 202102-01
      # https://circleci.com/developer/machine/image/android
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.04.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86

  firebase_app_distribution:
    executor: fastlane_executor
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"
      - ruby/install-deps
      - run:
          name: "Install Firebase CLI"
          command: |
            curl -sL firebase.tools | bash
      - run:
          name: Decode Android key store
          command: echo $BASE64_KEYSTORE | base64 -d | tee keystore app/keystore > /dev/null
      - run:
          name: "Deploy alpha version to Firebase"
          command: |
            bundle exec fastlane deploy_exp_to_firebase_app_distribution

workflows:
  local_test:
    jobs:
      - firebase_app_distribution
