default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end

  desc "fastlane 동작 테스트용"
  lane:test_for_test do |options|
    sh("echo test")
  end

  desc "린트 테스트"
  lane :lint_test do |options|
    gradle(
      task: "check",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  desc "유닛 테스트"
  lane :unit_test do |options|
    gradle(
      task: "test",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  # firebase app distribution 에 exp 배포하기
  desc "firebase app distribution 에 exp 배포하기"
  lane :deploy_exp_to_firebase_app_distribution do |options|
  # app id, token, group, branch 등 정보들 받을 수 있도록 하기

    gradle(
      task: 'assemble',
      build_type: 'debug',
       properties: {
                        "android.injected.signing.store.file" => ENV["RELEASE_KEYSTORE"],
                        "android.injected.signing.store.password" => ENV["RELEASE_STORE_PASSWORD"],
                        "android.injected.signing.key.alias" => ENV["RELEASE_KEY_ALIAS"],
                        "android.injected.signing.key.password" => ENV["RELEASE_KEY_PASSWORD"]
                   }
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      testers: "andy@channel.io, vvvvvoin@channel.io, aszx7009@gmail.com"
    )
  end

end



# play-console 에 production 배포하기