default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end

  desc "fastlane 동작 테스트용"
  lane:test_for_test do |options|
    sh("echo test")
  end

  desc "린트 테스트"
  lane :lint_test do |options|
    gradle(
      task: "check",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  desc "유닛 테스트"
  lane :unit_test do |options|
    gradle(
      task: "test",
      flavor: options[:build_flavor],
      build_type: options[:build_type]
    )
  end

  # firebase app distribution 에 exp 배포하기
  desc "firebase app distribution 에 exp 배포하기"
  lane :deploy_exp_to_firebase_app_distribution do |options|
  # app id, token, group, branch 등 정보들 받을 수 있도록 하기

    gradle(
      task: 'assemble',
      build_type: 'debug'
      properties: {
                "android.injected.signing.store.file" => :options[$key_store],
                "android.injected.signing.store.password" => :options[$key_store_password],
                "android.injected.signing.key.alias" => :options[$key_alias],
                "android.injected.signing.key.password" => :options[$key_password],
            }
    )

    firebase_app_distribution(
      app: options[:FIREBASE_APP_ID],
      firebase_cli_token: options[:FIREBASE_CLI_TOKEN],
      testers: "andy@channel.io, vvvvvoin@channel.io, aszx7009@gmail.com"
    )
  end

end



# play-console 에 production 배포하기